#
# Copyright (C) 2025 CESNET z.s.p.o.
#
# oarepo-requests is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.
#
#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create snapshot table."""

from __future__ import annotations

# revision identifiers, used by Alembic.
revision = "57aebe908bcb"
down_revision = "985368490c5b"
branch_labels = ()
depends_on = None


def upgrade() -> None:
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Note: the snapshots table has been removed altogether, but keeping the migration file.
    # See the git history for the previous implementation.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
